// mobile/src/pages/Register.tsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import api from "@/lib/api";
import { User, Lock, Eye, EyeOff, Mail, AlertCircle } from "lucide-react";

const Register = () => {
    const navigate = useNavigate();
    const [showPassword, setShowPassword] = useState(false);
    const [showConfirmPassword, setShowConfirmPassword] = useState(false);
    const [loading, setLoading] = useState(false);
    const [errors, setErrors] = useState<Record<string, string>>({});

    const [form, setForm] = useState({
        username: "",
        email: "",
        password: "",
        confirmPassword: "",
    });

    const validateForm = () => {
        const newErrors: Record<string, string> = {};

        // Username validation
        if (!form.username) {
            newErrors.username = "请输入用户名";
        } else if (form.username.length < 3 || form.username.length > 20) {
            newErrors.username = "用户名长度应在3-150个字符之间";
        } else if (!/^[a-zA-Z0-9_]+$/.test(form.username)) {
            newErrors.username = "用户名只能包含字母、数字和下划线";
        }

        // Email validation
        if (!form.email) {
            newErrors.email = "请输入邮箱";
        } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) {
            newErrors.email = "邮箱格式不正确";
        }

        // Password validation
        if (!form.password) {
            newErrors.password = "请输入密码";
        } else if (form.password.length < 6) {
            newErrors.password = "密码至少6位";
        }

        // Confirm password validation
        if (!form.confirmPassword) {
            newErrors.confirmPassword = "请再次输入密码";
        } else if (form.confirmPassword !== form.password) {
            newErrors.confirmPassword = "两次密码输入不一致";
        }

        setErrors(newErrors);
        return Object.keys(newErrors).length === 0;
    };

    const handleRegister = async (e: React.FormEvent) => {
        e.preventDefault();

        if (!validateForm()) {
            return;
        }

        setLoading(true);
        try {
            const { confirmPassword, ...registerData } = form;

            await api.post('auth/register/', registerData);

            // Save registration data for email verification
            localStorage.setItem("registerData", JSON.stringify(registerData));

            // Navigate to email verification page
            navigate(`/verify-email?email=${encodeURIComponent(registerData.email)}`);
        } catch (err: any) {
            const errorMsg = err.response?.data?.detail || err.response?.data?.message || "注册失败，请稍后重试";
            setErrors({ general: errorMsg });
        } finally {
            setLoading(false);
        }
    };

    const handleInputChange = (field: string, value: string) => {
        setForm({ ...form, [field]: value });
        // Clear error for this field when user starts typing
        if (errors[field]) {
            setErrors({ ...errors, [field]: "" });
        }
    };

    return (
        <div className="min-h-screen flex items-center justify-center bg-[#f5f5f7] px-4 py-6">
            <Card className="w-full max-w-[440px] p-12 rounded-3xl shadow-[0_4px_24px_rgba(0,0,0,0.06)] bg-white border-0">
                {/* Logo */}
                <div className="flex justify-center mb-8">
                    <div className="w-[72px] h-[72px] bg-[#1d1d1f] rounded-[18px] flex items-center justify-center">
                        <span className="text-white text-[32px] font-bold tracking-tight">F</span>
                    </div>
                </div>

                {/* Title */}
                <h1 className="text-[28px] font-bold text-center text-[#1d1d1f] mb-8 tracking-tight">
                    创建账户
                </h1>

                {/* Register Form */}
                <form onSubmit={handleRegister} className="space-y-4">
                    {/* Username */}
                    <div className="space-y-1">
                        <div className="relative">
                            <User className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-[#86868b]" />
                            <Input
                                type="text"
                                placeholder="请输入用户名 (3-150个字符)"
                                value={form.username}
                                onChange={(e) => handleInputChange("username", e.target.value)}
                                className={`pl-12 h-[52px] bg-[#f5f5f7] border-0 rounded-xl text-[15px] hover:bg-[#ebebed] focus:bg-[#ebebed] focus-visible:ring-[3px] focus-visible:ring-[rgba(0,122,255,0.1)] transition-all ${errors.username ? "ring-2 ring-red-500" : ""}`}
                            />
                        </div>
                        {errors.username && (
                            <p className="text-[13px] text-[#ff3b30] mt-1.5">{errors.username}</p>
                        )}
                    </div>

                    {/* Email */}
                    <div className="space-y-1">
                        <div className="relative">
                            <Mail className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-[#86868b]" />
                            <Input
                                type="email"
                                placeholder="请输入邮箱地址"
                                value={form.email}
                                onChange={(e) => handleInputChange("email", e.target.value)}
                                className={`pl-12 h-[52px] bg-[#f5f5f7] border-0 rounded-xl text-[15px] hover:bg-[#ebebed] focus:bg-[#ebebed] focus-visible:ring-[3px] focus-visible:ring-[rgba(0,122,255,0.1)] transition-all ${errors.email ? "ring-2 ring-red-500" : ""}`}
                            />
                        </div>
                        {errors.email && (
                            <p className="text-[13px] text-[#ff3b30] mt-1.5">{errors.email}</p>
                        )}
                    </div>

                    {/* Password */}
                    <div className="space-y-1">
                        <div className="relative">
                            <Lock className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-[#86868b]" />
                            <Input
                                type={showPassword ? "text" : "password"}
                                placeholder="请输入密码 (至少6位)"
                                value={form.password}
                                onChange={(e) => handleInputChange("password", e.target.value)}
                                className={`pl-12 pr-12 h-[52px] bg-[#f5f5f7] border-0 rounded-xl text-[15px] hover:bg-[#ebebed] focus:bg-[#ebebed] focus-visible:ring-[3px] focus-visible:ring-[rgba(0,122,255,0.1)] transition-all ${errors.password ? "ring-2 ring-red-500" : ""}`}
                            />
                            <button
                                type="button"
                                onClick={() => setShowPassword(!showPassword)}
                                className="absolute right-4 top-1/2 -translate-y-1/2 text-[#86868b] hover:text-[#1d1d1f] transition-colors"
                            >
                                {showPassword ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}
                            </button>
                        </div>
                        {errors.password && (
                            <p className="text-[13px] text-[#ff3b30] mt-1.5">{errors.password}</p>
                        )}
                    </div>

                    {/* Confirm Password */}
                    <div className="space-y-1">
                        <div className="relative">
                            <Lock className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-[#86868b]" />
                            <Input
                                type={showConfirmPassword ? "text" : "password"}
                                placeholder="请再次输入密码"
                                value={form.confirmPassword}
                                onChange={(e) => handleInputChange("confirmPassword", e.target.value)}
                                onKeyDown={(e) => e.key === "Enter" && handleRegister(e)}
                                className={`pl-12 pr-12 h-[52px] bg-[#f5f5f7] border-0 rounded-xl text-[15px] hover:bg-[#ebebed] focus:bg-[#ebebed] focus-visible:ring-[3px] focus-visible:ring-[rgba(0,122,255,0.1)] transition-all ${errors.confirmPassword ? "ring-2 ring-red-500" : ""}`}
                            />
                            <button
                                type="button"
                                onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                                className="absolute right-4 top-1/2 -translate-y-1/2 text-[#86868b] hover:text-[#1d1d1f] transition-colors"
                            >
                                {showConfirmPassword ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}
                            </button>
                        </div>
                        {errors.confirmPassword && (
                            <p className="text-[13px] text-[#ff3b30] mt-1.5">{errors.confirmPassword}</p>
                        )}
                    </div>

                    <div className="space-y-3 mt-6">
                        {errors.general && (
                            <Alert variant="destructive" className="mb-3">
                                <AlertCircle className="h-4 w-4" />
                                <AlertDescription>{errors.general}</AlertDescription>
                            </Alert>
                        )}

                        <Button
                            type="submit"
                            disabled={loading}
                            className="w-full h-[52px] bg-[#1d1d1f] hover:bg-[#1d1d1f] text-white rounded-xl text-base font-semibold shadow-[0_4px_16px_rgba(29,29,31,0.3)] hover:shadow-[0_8px_24px_rgba(29,29,31,0.4)] hover:-translate-y-0.5 hover:scale-[1.02] active:translate-y-0 active:scale-[0.98] transition-all duration-300 relative overflow-hidden before:absolute before:top-0 before:left-[-100%] before:w-full before:h-full before:bg-gradient-to-r before:from-transparent before:via-white/30 before:to-transparent before:transition-[left] before:duration-500 hover:before:left-[100%] disabled:opacity-70 disabled:cursor-not-allowed"
                        >
                            {loading ? "注册中..." : "注册"}
                        </Button>

                        <Button
                            type="button"
                            variant="outline"
                            onClick={() => navigate("/login")}
                            className="w-full h-[52px] bg-white/80 border-[#d2d2d7] hover:bg-white/80 hover:border-[#d2d2d7] text-[#1d1d1f] rounded-xl text-base font-medium hover:scale-[1.02] hover:shadow-[0_4px_12px_rgba(0,0,0,0.08)] active:scale-[0.98] transition-all duration-300"
                        >
                            已有账户? 立即登录
                        </Button>
                    </div>
                </form>
            </Card>
        </div>
    );
};

export default Register;

// frontend/src/views/auth/Register.vue
<template>
  <div class="register-page">
    <div class="register-card">
      <!-- Logo -->
      <div class="logo-container">
        <div class="logo">F</div>
      </div>

      <!-- Title -->
      <h1 class="title">创建账户</h1>

      <!-- Register Form -->
      <el-form 
        ref="formRef"
        :model="form" 
        :rules="rules"
        label-position="top"
        class="register-form"
        :hide-required-asterisk="true"
      >
<!--        <el-form-item label="用户名" prop="username">-->
        <el-form-item prop="username">
          <el-input 
            v-model="form.username" 
            placeholder="请输入用户名（3-20个字符）"
            size="large"
            clearable
          >
            <template #prefix>
              <el-icon><User /></el-icon>
            </template>
          </el-input>
        </el-form-item>

<!--        <el-form-item label="邮箱" prop="email">-->
        <el-form-item prop="email">
          <el-input 
            v-model="form.email" 
            type="email"
            placeholder="请输入邮箱地址"
            size="large"
            clearable
          >
            <template #prefix>
              <el-icon><Message /></el-icon>
            </template>
          </el-input>
        </el-form-item>

<!--        <el-form-item label="密码" prop="password">-->
        <el-form-item prop="password">
          <el-input 
            v-model="form.password" 
            :type="showPassword ? 'text' : 'password'"
            placeholder="请输入密码（至少6位）"
            size="large"
            clearable
          >
            <template #prefix>
              <el-icon><Lock /></el-icon>
            </template>
            <template #suffix>
              <el-icon 
                class="password-toggle" 
                @click="showPassword = !showPassword"
              >
                <View v-if="!showPassword" />
                <Hide v-else />
              </el-icon>
            </template>
          </el-input>
        </el-form-item>

<!--        <el-form-item label="确认密码" prop="confirmPassword">-->
        <el-form-item prop="confirmPassword">
          <el-input 
            v-model="form.confirmPassword" 
            :type="showConfirmPassword ? 'text' : 'password'"
            placeholder="请再次输入密码"
            size="large"
            clearable
            @keyup.enter="handleRegister"
          >
            <template #prefix>
              <el-icon><Lock /></el-icon>
            </template>
            <template #suffix>
              <el-icon 
                class="password-toggle" 
                @click="showConfirmPassword = !showConfirmPassword"
              >
                <View v-if="!showConfirmPassword" />
                <Hide v-else />
              </el-icon>
            </template>
          </el-input>
        </el-form-item>

        <div class="button-group">
          <el-button 
            type="primary" 
            size="large" 
            @click="handleRegister" 
            :loading="loading"
            :disabled="loading"
            class="register-button"
          >
            {{ loading ? '注册中...' : '注册' }}
          </el-button>

          <el-button 
            size="large" 
            @click="$router.push('/login')"
            class="login-button"
          >
            已有账户？去登录
          </el-button>
        </div>
      </el-form>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { useUserStore } from '../../stores/user';
import { useRouter } from 'vue-router';
import { ElMessage } from 'element-plus';
import { User, Lock, Message, View, Hide } from '@element-plus/icons-vue';

const userStore = useUserStore();
const router = useRouter();

const formRef = ref(null);
const form = ref({
  username: '',
  email: '',
  password: '',
  confirmPassword: ''
});
const loading = ref(false);
const showPassword = ref(false);
const showConfirmPassword = ref(false);

// 邮箱验证规则
const validateEmail = (rule, value, callback) => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!value) {
    callback(new Error('请输入邮箱地址'));
  } else if (!emailRegex.test(value)) {
    callback(new Error('请输入有效的邮箱地址'));
  } else {
    callback();
  }
};

// 确认密码验证规则
const validateConfirmPassword = (rule, value, callback) => {
  if (!value) {
    callback(new Error('请再次输入密码'));
  } else if (value !== form.value.password) {
    callback(new Error('两次输入的密码不一致'));
  } else {
    callback();
  }
};

// 表单验证规则
const rules = {
  username: [
    { required: true, message: '请输入用户名', trigger: 'blur' },
    { min: 3, max: 20, message: '用户名长度应为3-20个字符', trigger: 'blur' },
    { pattern: /^[a-zA-Z0-9_]+$/, message: '用户名只能包含字母、数字和下划线', trigger: 'blur' }
  ],
  email: [
    { required: true, validator: validateEmail, trigger: 'blur' }
  ],
  password: [
    { required: true, message: '请输入密码', trigger: 'blur' },
    { min: 6, message: '密码至少6位', trigger: 'blur' }
  ],
  confirmPassword: [
    { required: true, validator: validateConfirmPassword, trigger: 'blur' }
  ]
};

const handleRegister = async () => {
  // 验证表单
  if (!formRef.value) return;
  
  try {
    await formRef.value.validate();
  } catch (error) {
    ElMessage.warning('请正确填写表单信息');
    return;
  }

  loading.value = true;
  try {
    const { confirmPassword, ...registerData } = form.value;
    
    // 发送验证码
    await userStore.register(registerData);
    
    // 保存注册数据到本地存储（用于重新发送验证码）
    localStorage.setItem('registerData', JSON.stringify(registerData));
    
    ElMessage.success('验证码已发送到您的邮箱');
    
    // 跳转到验证页面
    router.push({
      path: '/verify-email',
      query: { email: registerData.email }
    });
  } catch (error) {
    const errorMsg = error.response?.data?.detail || error.response?.data?.message || '注册失败，请重试';
    ElMessage.error(errorMsg);
  } finally {
    loading.value = false;
  }
};
</script>

<style scoped>
.register-page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #f5f5f7;
  padding: var(--spacing-xl);
}

.register-card {
  background: white;
  border-radius: 24px;
  padding: 48px;
  width: 100%;
  max-width: 440px;
  box-shadow: 0 4px 24px rgba(0, 0, 0, 0.06);
}

.logo-container {
  display: flex;
  justify-content: center;
  margin-bottom: 32px;
}

.logo {
  width: 72px;
  height: 72px;
  background: #1d1d1f;
  border-radius: 18px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 32px;
  font-weight: 700;
  color: white;
  letter-spacing: -0.02em;
}

.title {
  font-size: 28px;
  font-weight: 700;
  text-align: center;
  color: #1d1d1f;
  margin-bottom: 8px;
  letter-spacing: -0.02em;
}

.subtitle {
  font-size: 15px;
  text-align: center;
  color: #86868b;
  margin-bottom: 32px;
}

.register-form {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.register-form :deep(.el-form-item) {
  margin-bottom: 16px;
}



.register-form :deep(.el-form-item__label) {
  font-size: 14px;
  font-weight: 600;
  color: #1d1d1f;
  margin-bottom: 8px;
  padding: 0;
  line-height: 1.5;
}

.register-form :deep(.el-form-item__error) {
  font-size: 13px;
  margin-top: 6px;
  color: #ff3b30;
}

.register-form :deep(.el-input__wrapper) {
  background-color: #f5f5f7;
  border: none;
  box-shadow: none;
  border-radius: 12px;
  padding: 12px 16px;
  transition: all 0.2s ease;
}

.register-form :deep(.el-input__wrapper:hover) {
  background-color: #ebebed;
}

.register-form :deep(.el-input__wrapper.is-focus) {
  background-color: #ebebed;
  box-shadow: 0 0 0 3px rgba(0, 122, 255, 0.1);
}

.register-form :deep(.el-input__inner) {
  font-size: 15px;
}

.register-form :deep(.el-input__prefix),
.register-form :deep(.el-input__suffix) {
  color: #86868b;
}

.password-toggle {
  cursor: pointer;
  transition: color 0.2s ease;
}

.password-toggle:hover {
  color: #1d1d1f;
}

.button-group {
  display: flex;
  flex-direction: column;
  gap: 12px;
  margin-top: 8px;
  align-items: stretch;
}

.button-group .el-button + .el-button {
  margin-left: 0;
}

.register-button {
  width: 100%;
  height: 52px;
  background: #1d1d1f;
  border: none;
  border-radius: 12px;
  font-size: 16px;
  font-weight: 600;
  letter-spacing: -0.01em;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  box-shadow: 0 4px 16px rgba(29, 29, 31, 0.3);
  position: relative;
  overflow: hidden;
}

.register-button::before {
  content: '';
  position: absolute;
  top: 0;
  left: -100%;
  width: 100%;
  height: 100%;
  background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.3), transparent);
  transition: left 0.5s ease;
}

.register-button:hover::before {
  left: 100%;
}

.register-button:hover {
  transform: translateY(-2px) scale(1.02);
  box-shadow: 0 8px 24px rgba(29, 29, 31, 0.4);
}

.register-button:active {
  transform: translateY(0) scale(0.98);
}

.register-button:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}

.login-button {
  width: 100%;
  height: 52px;
  background: rgba(255, 255, 255, 0.8);
  border: 1px solid #d2d2d7;
  border-radius: 12px;
  font-size: 16px;
  font-weight: 500;
  color: #1d1d1f;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

.login-button:hover {
  background: rgba(255, 255, 255, 0.8) !important;
  border-color: #d2d2d7 !important;
  color: #1d1d1f !important;
  transform: scale(1.02);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
}

.login-button:active {
  transform: scale(0.98);
}

@media (max-width: 768px) {
  .register-card {
    padding: 32px 24px;
  }

  .title {
    font-size: 24px;
  }
}
</style>
```
